version: 1
labels:
  - label: "WIP"
    title: "^WIP:.*"
  - label: "feature"
    branch: "^feature/.*"
  - label: "bugfix"
    branch: "^bugfix/.*"
  - label: "hotfix"
    branch: "^hotfix/.*"
  - label: "enhancement"
    branch: "^enhance/.*"
  - label: "need-to-change-branch-name"
    branch: "^(?!^feature/.*$)(?!^bugfix/.*$)(?!^hotfix/.*$)(?!^enhance/.*$)(?!^style/.*$)(?!^docs/.*$).*$"
