version: "3"

services:
  sink-data-subscriber:
    platform: linux/amd64
    build:
      context: ./docker/sink
      dockerfile: Dockerfile
    container_name: sink-data-subscriber

networks:
  default:
    name: mlo-mle-network
