version: "3"

services:
  sink-data-subscriber:
    depends_on:
      - api-with-model
    platform: linux/amd64
    build:
      context: ./docker/sink
      dockerfile: Dockerfile
    container_name: sink-data-subscriber

networks:
  default:
    name: ch1_default
    external: true
