version: "3"

services:
  data-subscriber:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: data-subscriber
  grafana-dashboard:
    image: grafana/grafana
    ports:
     - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: dashboarduser
      GF_SECURITY_ADMIN_PASSWORD: dashboardpw

networks:
  default:
    name: mlops-network
    external: true
