version: "3"

services:
  db:
    image: postgres:14.0
    container_name: postgres-server
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      TZ: Asia/Seoul
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: data-generator-server
    environment:
      TZ: Asia/Seoul
<<<<<<< HEAD
    command: ["bash", "-c", "python create_table.py --db-host db;python generate_data.py --db-host db"]
=======
>>>>>>> b9622ef (CMD to dockerfile)
    depends_on:
      db:
        condition: service_healthy
